version: "3"
services:
  app:
    build: ./client/.
    volumes:
      - ./client/:/app
    ports:
      - "3000:3000"
    command: ash -c "npm run dev"
  api:
    build: ./server/.
    volumes:
      - ./server/:/app
    ports:
      - "5042:5042"
    command: /bin/sh -c "pipenv run serve"
